// action types for the entire application

export const FETCH_TO_DO_LIST_START = 'FETCH_TO_DO_LIST_START'
export const FETCH_TO_DO_LIST_SUCCESS = 'FETCH_TO_DO_LIST_SUCCESS'
export const FETCH_TO_DO_LIST_FAILURE = 'FETCH_TO_DO_LIST_FAILURE'

export const SEARCH_TO_DO_ITEM_START = 'SEARCH_TO_DO_ITEM_START'
export const SEARCH_TO_DO_ITEM_SUCCESS = 'SEARCH_TO_DO_ITEM_SUCCESS'
export const SEARCH_TO_DO_ITEM_FAILURE = 'SEARCH_TO_DO_ITEM_FAILURE'

export const REMOVE_ITEM_FROM_TODO_LIST = 'REMOVE_ITEM_FROM_TODO_LIST'
export const REMOVE_ITEM_FROM_IMPORTANT_LIST = 'REMOVE_ITEM_FROM_IMPORTANT_LIST'

export const TOOGLE_STATE_INPUT_ADD = 'TOOGLE_STATE_INPUT_ADD'
export const TOOGLE_STATE_INPUT_ADD_VIDEO = 'TOOGLE_STATE_INPUT_ADD_VIDEO'

export const ADD_NEW_ITEM = 'ADD_NEW_ITEM'
export const ADD_NEW_VIDEO = 'ADD_NEW_VIDEO'

export const CLEAN_COMPLETED_LIST = 'CLEAN_COMPLETED_LIST'

export const SHOW_PLUS_FOR_ADD_NEW_ITEM = 'SHOW_PLUS_FOR_ADD_NEW_ITEM'

export const TOOGLE_STATE_IMPORTANT_ITEM = 'TOOGLE_STATE_IMPORTANT_ITEM'
export const TOOGLE_STATE_COMPLETED_ITEM = 'TOOGLE_STATE_COMPLETED_ITEM'

export const SET_PAGE_NAME = 'SET_PAGE_NAME'



